Pull changes from android-ci branch

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -39,21 +39,22 @@ jobs:
       - name: Conan export all packages
         run: python scripts/conan_export_all_packages.py
 
+      # Generate dependency trees for all disjoined trees
       - run: conan graph info recipes/odrcore/all/conanfile.py --version=4.0.0 --profile:host=android-21-armv8 --format=json | tee odrcore-dependency-tree.json
-        shell: bash # bash will pipefail on error
+        shell: bash # bash shell needed to pipefail on error
       - run: conan graph info recipes/poppler-data/all/conanfile.py --version=0.4.12 --profile:host=android-21-armv8 --format=json | tee pdf2htmlEX-dependency-tree.json
-        shell: bash # bash will pipefail on error
+        shell: bash # bash shell needed to pipefail on error
 
       - name: Get a list of commits that triggered this workflow
         id: commit-list
-        shell: bash # bash will pipefail on error
+        shell: bash # bash shell needed to pipefail on error
         run: python scripts/get_commits_from_github_event.py | tee $GITHUB_OUTPUT
         env:
           GITHUB_EVENT: ${{ toJson(github.event) }}
 
       - name: List all modified packages in GitHub Actions format
         id: list-packages
-        shell: bash # bash will pipefail on error
+        shell: bash # bash shell needed to pipefail on error
         run: python scripts/list_package_versions.py --github --git-modified ${{ steps.commit-list.outputs.commits }} --modified-tree odrcore-dependency-tree.json pdf2htmlEX-dependency-tree.json | tee $GITHUB_OUTPUT
 
   build:
